runtime: nodejs14 # 使用するNode.jsのバージョンを指定

env: standard # スタンダード環境を使用

instance_class: F1 # インスタンスのクラスを指定

automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 5 # 最大インスタンス数を指定

entrypoint: node index.js # アプリケーションの起動コマンドを指定

