runtime: custom
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  target_cpu_utilization: 0.65
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.5

env_variables:
  NODE_VERSION: '20.11.0'

